### ISSUE TITLE
[Validators] Validators list

### ISSUE THREAD

**Issue by mitchellchou** [oursky/likedao#102]
## Acceptance criteria
- [x] I can see validators filter by all/active/inactive
- [x] Click its name and enter its validator details page
- [ ] Support pagination (page size = 20)
- [x] Participation = How many proposals has S/he voted / How many proposals we have(count from no.1 proposal)

## Test flow
Check the bigdipper data see if they're correct

## Design
![image.png](https://zube.io/files/oursky/967e3c51429b457bf9f938ad615b2926-image.png)

## Remarks
1. Please use `STAKED` instead of STAKE to indicate that's the amount I delegated to this validator
2. Please ignore the filter of voting power and the separated listing of 30% voting power because there's no validator have voting power of more than 30%
3. Search will be done later

**Comment by chihimng** [comment]
- Backend: Add graphql schema / query for validators, Add dataloader / db query for validators & filter / pagination / sorting [6]
- UI: Implement table view, filter tab [6]
- UI: Implement pagination, sorting [6]
- Additional data: user's stake, rewards, expected returns [3]

question:
for participation, show count of validator's votes vs total proposal count since validator's inception instead of all time?
for uptime rate, show missed blocks / (total blocks - start height)

**Comment by mitchellchou** [comment]
1. Go with: show count of validator's votes vs total proposal count since validator's inception (will ask kin ko first)
2. Check jail time (from cosmos sdk)

**Comment by rickmak** [comment]
The uptime should calculate against the slashing module `SignedBlockWindow` config. refs: https://docs.cosmos.network/master/modules/slashing/08_params.html

**Comment by hochiw** [comment]
@mitchellchou is every column sortable?

**Comment by mitchellchou** [comment]
@hochiw 
Yes should be sortable
Can we make it random sorting by default? (request by Kin Ko)
(I guess Kin Ko doesn't want to have validators always on the top of the list)

**Comment by hochiw** [comment]
@mitchellchou I realized we might not be able to sort some of the fields, because some of the data is actually from rpc (stake, rewards, participations, expected returns, uptime), tho some of them can be calculated in backend (participations and uptime), but for the rest of them we won't be able to sort by them unless we handle pagination in front end :sadFrog:
