### ISSUE TITLE
Add reaction table to server db

### ISSUE THREAD

**Issue by hochiw** [oursky/likedao#114]
```
CREATE TABLE reaction (
    id string,
    reaction varchar,
    user varchar,
    createdAt timestamp,
    updatedAt timestamp
)

CREATE TABLE proposals (
    id string
    proposalId int,
    createdAt timestamp,
    updatedAt timestamp
)

CREATE TABLE reaction_proposals (
    id string,
    reaction_id string,
    proposal_id string,
    createdAt timestamp,
)
```

**Comment by chihimng** [comment]
use ulid for primary key?

**Comment by chihimng** [comment]
also, there will be reactions to other items later? e.g. posts / comments

**Comment by hochiw** [comment]
right, how about we handle it using m2m with the right hand side synchronized when we add the first reaction associated to it?

**Comment by rickmak** [comment]
Sorry, I don't understand what is `with the right hand side synchronized when we add the first reaction associated to it?`

ULID is good.

**Comment by hochiw** [comment]
since the reaction can be used for proposals, posts, comments I think we would create association table for each relationship?

**Comment by rickmak** [comment]
Still not understand. Might be sketch an ER diagram?

**Comment by hochiw** [comment]
Just not very sure if we should make it traditional despite having no reference to proposal_id, post_id and comment_id since they will probably be on bdjuno's db 

![Untitled Diagram.drawio.png](https://zube.io/files/oursky/c2360361fc6580a91aac89cd98f4afc0-untitled-diagram-drawio.png)

or just put everything together

![Untitled Diagram.drawio(1).png](https://zube.io/files/oursky/549924a3d8661b1bec85f1d54aac7c1c-untitled-diagram-drawio1.png)

**Comment by rickmak** [comment]
I am definitely against the first solution, no way to create a `reactions` table just storing a string.

Second is fine.

How about

|Reaction|   |   |
|---|---|---|
|ID|ulid|required|
|reaction|UNICODECHAR|required|
|address|bech32|required|
|target_id|string|required|
|target_type|string|required|
|created_at|timestamp|required|
|updated_at|timestamp|required|

Index on (target_id,target_type)

Why we do this?

Query scenario:

1. Query all reaction on a post/comment/proposal -> No much different for all three solution
3. Query all reaction on specific address -> one simple query for my solution vs 3 query.

Write scenario:

1. React to a post/comment/proposal -> same

Drawback
1. Lack of foreign key protection
2. because no foreign key, no cascade delete. There will be orphan reactions.

Goody
No DB change if we add more reaction to different type.
