### ISSUE TITLE
Update index.html description

### ISSUE THREAD

**Issue by hochiw** [oursky/likedao#147]

**Comment by mitchellchou** [comment]
@Rico-Wong 

stake.like.co don't have walletconnect so I checked Osmosis
![image.png](https://zube.io/files/oursky/2da645496fc867474f438378c1e0f23e-image.png)

I think no special handling is needed?

**Comment by ivanng-oursky** [comment]
@Rico-Wong would we want to have the ability to modify the title and other meta data (like descriptions) using some kind of configuration file or env variables, rather than just hard coding the values in index.html? Similar to what will be done in #255?

If yes, https://github.com/vbenjs/vite-plugin-html seems to be able to do the trick, but it feels a bit hacky? Kinda like a half done SSR.

**Comment by mitchellchou** [comment]
just remind them to revise this document
